### PR TITLE
Added new repo ServerlessWorkFlow & Decisioning CoP

### PR DESCRIPTION
**Pull request by pamenon**

### CODE REVIEW

**Comment by sabre1041** [comment]
@pamenon can you create an Issue and associate it with this PR. The issue should have the appropriate fields for the description for the newly created repository and member details (should associate with the members that you have included in this PR)

**Comment by sabre1041** [comment]
@pamenon is there a need to create a separate team that is dedicated to just this repository or can an existing team be reused?

**Comment by pamenon** [comment]
@sabre1041 updated the issue. The maintainer will be part of the existing team, 
maintainers:
          - pamenon
          - erouvas
          - pauljamesbrown.

**Comment by sabre1041** [comment]
Depends on #496

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
