### PR TITLE
Added bszeti, ckavili & lpsantil as CoP members

### LINKED ISSUE #181: Please add me as a member of the redhat-cop organization
I would like to become a general contributor to the Red Hat Communities of Practice GitHub Organization

---

Review request:

cc: @redhat-cop/container-cop-core

### PR DESCRIPTION
**Pull request by pabrahamsson**
Add new members bszeti, ckavili & lpsantil as CoP members, fixes #181, #182, #183

### CODE REVIEW

**Comment by sabre1041** [comment]
@pabrahamsson do we want to add them to the `container-cop` team as well?

**Comment by pabrahamsson** [comment]
Sure will do @sabre1041

**Pull request merged**
