### PR TITLE
added ansible-openshift-virt-day2 repo team

### PR DESCRIPTION
**Pull request by bontreger**
Need to add a new repository for creating Ansible content for managing day 2 operations of OCP Virt

### CODE REVIEW

**Comment by bontreger** [comment]
think i did this wrong, reopening a new PR

**Comment by sabre1041** [comment]
@bontreger repositories themselves are not being tracked via Peribolos, only the team management and the association to repositories. You can make a new request for a repository by creating a new issue [here](https://github.com/redhat-cop/org/issues/new?assignees=&labels=access&projects=&template=repository-management.md&title=)

**Comment by garethahealy** [comment]
@bontreger is this repo still needed/wanted? if so, can you raise an issue as per Andys above comment

**Comment by garethahealy** [comment]
no movement - closing. if its still needed please create an issue/re-open

**Pull request closed without merging**
