### PR TITLE
removed ansible-middleware team

### PR DESCRIPTION
**Pull request by garethahealy**
all the repos under that team have been achieved and migrated into another org.

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
LGTM

**Review by sabre1041 — DISMISSED** [review]
LGTM. bittersweet

**Review by sabre1041 — CHANGES_REQUESTED** [review]
@garethahealy can the conflicts be addressed?

**Comment by garethahealy** [comment]
done

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
