### PR TITLE
Add chadhellyea as CoP member

### LINKED ISSUE #337: Please add me as a member of the redhat-cop organization
I would like to become a general contributor to the Red Hat Communities of Practice GitHub Organization

---

Review request:

cc: @redhat-cop/container-cop-core

### PR DESCRIPTION
**Pull request by pabrahamsson**
Resolves #337

### CODE REVIEW

**Comment by sabre1041** [comment]
@pabrahamsson can you also add as a member of `rhel-edge-automation-arch`? It was added as a comment which you might have missed

**Comment by pabrahamsson** [comment]
> @pabrahamsson can you also add as a member of `rhel-edge-automation-arch`? It was added as a comment which you might have missed

My bad, updated PR incoming

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
