### PR TITLE
Add quay images for devspaces-images repo

### PR DESCRIPTION
**Pull request by etsauer**
@cgruver do you think we need any other image repos?

### CODE REVIEW

**Comment by etsauer** [comment]
@sabre1041 @oybed question on the automation here. Is it possible to set these image repos up to share the pushbot account?

**Comment by oybed** [comment]
@etsauer if I follow your question right, the robot account is already shared between repos ... as long as the robot name matches between repos - it is the one and the same robot account use.

**Comment by oybed** [comment]
Automation to create the robot account at an org level:
https://github.com/redhat-cop/infra-ansible/blob/main/roles/scm/quay/tasks/manage_robot.yml

... automation to assign the org level robot to the specified repo:
https://github.com/redhat-cop/infra-ansible/blob/main/roles/scm/quay/tasks/manage_repository.yml#L41-L52

**Comment by garethahealy** [comment]
@etsauer did @oybed answer your question? good to merge?

**Pull request merged**
