### PR TITLE
create triage team for container-cop, add pfeifferj

### PR DESCRIPTION
**Pull request by pfeifferj**

### CODE REVIEW

**Comment by garethahealy** [comment]
@sabre1041 @pabrahamsson ; cant see anywhere else we use `triage` - is this a flow/role we want to add in?
- https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by pabrahamsson** [comment]
I certainly wasn't aware of the `triage` role, looks like it could be useful. No objection from me.

**Comment by pfeifferj** [comment]
can we merge the PR? :)

**Comment by pabrahamsson** [comment]
@pfeifferj I'd like @sabre1041 to take a look before we merge.

**Review by sabre1041 — APPROVED** [review]
/LGTM

**Pull request merged**
