### PR TITLE
removing old gpte members mid-2023

### PR DESCRIPTION
**Pull request by 9strands**
Removing ex Redhatters or ex-team-members from GPTE group.

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by garethahealy** [comment]
have these people only left GPTE or RH as well? if they've left RH, they should be removed as members of the org as well.

**Comment by sabre1041** [comment]
@garethahealy looks to be a mix of both

**Comment by 9strands** [comment]
Hi, @sabre1041 @garethahealy - 

Left RH to my ability to see
          - evisb
          - gmontalvoy
          - thomas-crowe

Left GPTE
          - varodrig

**Pull request merged**
