### PR TITLE
Updating new members for Agnosticd-core membership from RHDP team

### PR DESCRIPTION
**Pull request by 9strands**
Adding members of the RHDP team to agnosticd-core team to increase coverage.

### CODE REVIEW

**Comment by 9strands** [comment]
Adding additional members to agnosticd-core team for additional geo-coverage.

**Comment by garethahealy** [comment]
can one of you approve? @jkupferer @tonykay @wkulhanek

**Comment by 9strands** [comment]
@garethahealy - I spoke with @tonykay last night, he tried to approve, but when logging in, he has no "approve" button available.  Should @tonykay just comment here that he approves?

**Comment by garethahealy** [comment]
@9strands ; yep, a comment is fine.

**Review by tonykay — APPROVED** [review]

**Comment by 9strands** [comment]
@garethahealy - approved by @tonykay - over to you!

**Comment by 9strands** [comment]
Note: reverted by @fridim after follow up discussion with pre-existing agnosticd-core members in https://github.com/redhat-cop/org/pull/775.

The added users were moved to GPTE Admins so that they can disable branch protections in agnosticd instead of being an additional member of agnosticd-core and can force commits at need instead of the original incident solution of adding people to agnosticd-core.

**Pull request merged**
