### PR TITLE
add itewk as member of day-in-the-life

### PR DESCRIPTION
**Pull request by itewk**

### CODE REVIEW

**Comment by garethahealy** [comment]
@itewk ; is there a reason to be added to this team? as being added gives you the below, which doesn't change any perms if you are expecting it to...

```
cluster-lifecycle: read
git-flow: read
gows: read
helm-charts: read
ninja-points: read
openshift-management: read
rego-policies: read
```

**Comment by itewk** [comment]
@garethahealy already spoke with @sabre1041 and he said to put this in. but the reason is so i can review / merge changes against helm chart i maintain in helm-charts

**Comment by sabre1041** [comment]
> @garethahealy already spoke with @sabre1041 and he said to put this in. but the reason is so i can review / merge changes against helm chart i maintain in helm-charts
> 

@garethahealy to what @ianwatsonrh said. However if @itewk can create an issue so that we can track it. That also would be good. 

As a maintainer of the cop (under containers) the tooling that is within this space is content that @itewk already contributes to

**Comment by garethahealy** [comment]
ye, i dont think thats going to give you merge rights in the top-level team, think you need to be added into this members section:
- https://github.com/redhat-cop/org/blob/4d01a2d25e3626f8687d8b235a7186dc3b841998/config.yaml#L853-L868

but will merge and see what happens.

**Comment by itewk** [comment]
@garethahealy adding myself as a member of `day-in-the-life` was what this PR did, but that didn't seem to give me any more permissions in the repo. Do i need to be maintiner?

**Comment by garethahealy** [comment]
like i said [here](https://github.com/redhat-cop/org/pull/943#issuecomment-2493307711), you need to be a member of `day-in-the-life-mergers`

**Comment by itewk** [comment]
i was not doing criticle reading and seeing the difference between `day-in-the-life` and `day-in-the-life-mergers` new PR coming.

**Comment by itewk** [comment]
https://github.com/redhat-cop/org/pull/945

**Pull request merged**
