### PR TITLE
Add k8s_config

### PR DESCRIPTION
**Pull request by jkupferer**
Add repository for k8s_config ansible role.

### CODE REVIEW

**Comment by sabre1041** [comment]
@jkupferer there is a formal repository request template (see [this](https://github.com/redhat-cop/org/issues/new/choose)). 

Would you be able to update the description to align with the template?

**Comment by jkupferer** [comment]
@sabre1041 I've submitted an issue... should I update the PR as well to match the issue?
https://github.com/redhat-cop/org/issues/77

**Comment by sabre1041** [comment]
@jkupferer Repository created: https://github.com/redhat-cop/k8s_config

Feel free to update the PR and remove the WIP status when you feel it is ready to review

**Comment by jkupferer** [comment]
WIP status removed. I came up with this configuration by simply referencing the way `babylon` was configured... though I have to admit I don't follow the logic of this yaml structure.

**Pull request merged**
