### PR TITLE
Adding new maintainer to BusinessAutomation cop

### PR DESCRIPTION
**Pull request by ally-jarrett**
I'm a BA CoP manager with @pamenon, so adding myself as a maintainer

### CODE REVIEW

**Comment by pamenon** [comment]
Yes, it's all fine for me. 
I and Ally are Business Automation CoP Managers, we will work together as maintainers in the businessautoamtion-cop repo. Could you please go ahead and merger this change?

**Comment by ally-jarrett** [comment]
@pabrahamsson can we get this approved?

**Comment by pamenon** [comment]
@pabrahamsson for some reason,  @ally-jarrett  was removed as part of the businessautomation-cop repo team, could you please add him back as a maintainer.
Thanks in advance

**Comment by oybed** [comment]
image

@pamenon @ally-jarrett you should be all set ^^

**Pull request merged**
