### PR TITLE
Update gpte team members

### PR DESCRIPTION
**Pull request by jkupferer**

### CODE REVIEW

**Review by wkulhanek — APPROVED** [review]

**Comment by jkupferer** [comment]
The `org-validate-configs` test shows failed, but I can't see details.

**Comment by pabrahamsson** [comment]
I'll take a look at this later today @jkupferer

**Comment by pabrahamsson** [comment]
@jkupferer there's supposed to be a link to the failed (or successful job) but for some reason that's not there. I was able to to dig out the error and I think you also need to make some of them members of the redhat-cop org (also in config.yaml).
>{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure redhat-cop members: all team members/maintainers must also be org members: d-jana, gmontalvoy, marcosmamorim, prakhar1985, wilson-walrus","time":"2021-05-26T14:34:14Z"}

**Comment by jkupferer** [comment]
Thanks @pabrahamsson I've added the missing users to the org.

**Review by pabrahamsson — APPROVED** [review]
/lgtm

**Pull request merged**
