### PR TITLE
added andrew-jones and YoNoSoyVictor

### PR DESCRIPTION
**Pull request by bbethell-1**
Add users -Victor and Andrew

### CODE REVIEW

**Comment by garethahealy** [comment]
Both those users need to link their GitHub ID with LDAP, see:
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Comment by 9strands** [comment]
Hi, @garethahealy - we'll ask that they do that.  In the mean-time, as an existing member, I can confirm that both of these are new team-members for our team.

**Review by djdanielsson — APPROVED** [review]
LGTM once they add their GitHub to LDAP

**Comment by bbethell-1** [comment]
I can confirm that both Andrew and Victor have added the ID to rover now @djdanielsson

**Comment by garethahealy** [comment]
ldapsearch is not showing for @andrew-jones:

```
ldapsearch -x -h ldap.corp.redhat.com -b dc=redhat,dc=com -s sub 'rhatSocialURL=Github->*andrew-jones*'
# extended LDIF
#
# LDAPv3
# base <dc=redhat,dc=com> with scope subtree
# filter: rhatSocialURL=Github->*andrew-jones*
# requesting: ALL
#

# search result
search: 2
result: 0 Success

# numResponses: 1
```

It finds @yonosoyvictor

**Comment by andrew-jones** [comment]
Hi @garethahealy, can you check now please.  I've updated rover.

Thanks
Andrew

**Comment by andrew-jones** [comment]
@garethahealy thanks for the merge.  I'm still having issues pushing a new branch to the agnosticd repo.  Any ideas if I have missed something?

`
andrew@fedora:~/src/github.com/redhat-cop/agnosticd$ git fetch -p
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 24 (delta 10), reused 18 (delta 10), pack-reused 0 (from 0)
Unpacking objects: 100% (24/24), 14.54 KiB | 1.45 MiB/s, done.
From github.com:redhat-cop/agnosticd
   403cb1d28..b700a3656  development -> origin/development
   803868996..2dfadc8bc  gh-pages    -> origin/gh-pages

andrew@fedora:~/src/github.com/redhat-cop/agnosticd$ git push origin andrew-jones-patch-1 
ERROR: Permission to redhat-cop/agnosticd.git denied to andrew-jones.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by garethahealy** [comment]
@andrew-jones ; you should of got a github email to accept the invitation to join the org. you need to accept that.
Screenshot 2024-10-11 at 08 08 45

**Pull request merged**
