### PR TITLE
New RHDP team member access

### PR DESCRIPTION
**Pull request by andrew-jones**

### CODE REVIEW

**Review by ashokjammula1 — APPROVED** [review]
Hi, Harsh is the new Red Hat Demo Platform  team member, he works on redhat-cop on daily basis. kindly approve the PR

**Comment by garethahealy** [comment]
cant find @hararora123 via LDAP
- https://source.redhat.com/departments/it/it-information-security/wiki/details_about_rover_github_information_security_and_scanning

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by djdanielsson** [comment]
sorry didn't see the tag on mobile until after I hit merge

**Pull request merged**
